
CREATE DATABASE `ilcs` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

USE `ilcs`;


CREATE TABLE `t_vehicle` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `VEHICLE_NAME` varchar(50) NOT NULL,
  `VEHICLE_TYPE` enum('V','N','S') NOT NULL,
  `PRICE` decimal(15,2) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


INSERT INTO `t_vehicle` (`ID`, `VEHICLE_NAME`, `VEHICLE_TYPE`, `PRICE`) VALUES
(1, 'Vario', 'V', 10000000),
(2, 'Nmax', 'N', 10000000),
(3, 'SatriaFU', 'S', 10000000);


CREATE TABLE `t_installment` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `INSTALLMENT_TIME` int NOT NULL,
  `INSTALLMENT_FEE` decimal(5,2) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


INSERT INTO `t_installment` (`ID`, `INSTALLMENT_TIME`, `INSTALLMENT_FEE`) VALUES
(1, 5, 0.3),
(2, 10, 0.5),
(3, 15, 0.8);


CREATE TABLE `t_transaction` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `BUYER_NAME` varchar(50) NOT NULL,
  `TX_DATE` date NOT NULL,
  `VEHICLE_TYPE` enum('V','N','S') NOT NULL,
  `INSTALLMENT` int NOT NULL,
  `TOTAL_PRICE` decimal(15,2) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
